name: perform-code-checkings

on:
  push:
    branches: '*'
    tags: '*'
    paths-ignore: '**.md'

  pull_request:
    branches: '*'
    tags: '*'
    paths-ignore: '**.md'

jobs:
  code-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        uses: snok/install-poetry@v1.3.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache venv
        id: code-check-cache
        uses: actions/cache@v3
        with:
          path: app/.venv
          key: code-check-python-${{ matrix.python-version }}-${{ hashFiles('app/poetry.lock') }}

      - name: Install dependencies
        if: steps.code-check-cache.outputs.cache-hit != 'true'
        run: cd app && poetry install

      - name: Check code style
        run: make poe task=check:style

      - name: Check lint
        run: make poe task=check:lint

      - name: Check types
        run: make poe task=check:types

      - name: Check security issues
        run: make poe task=check:security

      - name: Check for dead code
        run: make poe task=check:deadcode
