name: run-tests-and-upload-coverage

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths-ignore:
      - '**.rst'
  pull_request:
    branches:
      - '*'
    tags:
      - '*'
    paths-ignore:
      - '**.rst'

jobs:
  test-with-cov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install poetry
        run: python -m pip install --upgrade poetry

      - name: Install python dependencies
        run: poetry install

      - name: Run unit tests
        run: poetry run poe tests

      - name: Upload coverage results
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          verbose: true
